export const FETCH_GOALS = 'FETCH_GOALS';
export const GOALS_HAS_ERRORED = 'GOALS_HAS_ERRORED';
export const GOALS_IS_LOADING = 'GOALS_IS_LOADING';
export const GOALS_FETCH_DATA_SUCCESS = 'GOALS_FETCH_DATA_SUCCESS';
export const GOAL_POST_DATA = 'GOAL_POST_DATA';